name: Run

on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        required: true
      password:
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Hide inputs
        run: |
          USERNAME=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.username' )
          echo "::add-mask::$USERNAME"
          PASSWORD=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.password' )
          echo "::add-mask::$PASSWORD"

      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py "${{ inputs.username }}" "${{ inputs.password }}"
